// This file was generated by a custom prisma generator, do not edit manually.
export const CommentEntityType = {
  MARKET: 'MARKET',
  LIST: 'LIST',
} as const

export type CommentEntityType = (typeof CommentEntityType)[keyof typeof CommentEntityType]
