export const INITIAL_MARKET_LIQUIDITY_PRIMARY = 500
export const LOWEST_MARKET_LIQUIDITY_PRIMARY = 200

export const LIQUIDITY_VOLUME_BONUS_PERCENT = 0.05

export const UNIQUE_TRADER_BONUS_PRIMARY = 50
export const UNIQUE_TRADER_LIQUIDITY_PRIMARY = 50

export const INITIAL_USER_BALANCE_PRIMARY = 20000

export const DAILY_TRADE_BONUS_PRIMARY = 100
export const DAILY_MARKET_BONUS_PRIMARY = 500
export const DAILY_COMMENT_BONUS_PRIMARY = 50
export const DAILY_LIQUIDITY_BONUS_PRIMARY = 250

export const REALIZED_GAINS_TAX = 0.05
