export const INITIAL_MARKET_LIQUIDITY_PRIMARY = 1000

export const UNIQUE_TRADER_BONUS_PRIMARY = 50
export const UNIQUE_TRADER_LIQUIDITY_PRIMARY = 50

export const INITIAL_USER_BALANCE_PRIMARY = 50000
